#ifndef VFS_H
#define VFS_H

/* Simple embedded VFS API (data generated by tools/embed_vfs.py into net/vfs.c) */

void vfs_init(void);
int vfs_ls(const char* path); /* prints entries under path, returns count */
int vfs_cd(const char* path); /* change current directory, return 0 on success */
const char* vfs_readfile(const char* path); /* returns pointer to content or NULL */
int vfs_file_size(const char* path);
const char* vfs_get_cwd(void);

#endif
